# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

ActiveRecord::Base.transaction do 
  User.destroy_all 
  bueller   = User.create!(username: 'bueller',   email: 'b@b.com',             password: 'password') 
  sloane    = User.create!(username: 'sloane',    email: 's@b.com',             password: 'password') 
  cameron   = User.create!(username: 'cameron',   email: 'c@b.com',             password: 'password') 
  rooney    = User.create!(username: 'rooney',    email: 'r@b.com',             password: 'password') 
  jeanie    = User.create!(username: 'jeanie',    email: 'j@b.com',             password: 'password') 
  dethklok  = User.create!(username: 'dethklok',  email: 'deth@klok.com',       password: 'password') 
  pentakill = User.create!(username: 'pentakill', email: 'penta@kill.com',      password: 'password') 
  etc       = User.create!(username: 'etc',       email: 'etc@blizz.com',       password: 'password') 
  sylvanas  = User.create!(username: 'sylvanas',  email: 'sylvanas@blizz.com',  password: 'password') 
  thrall    = User.create!(username: 'thrall',    email: 'thrall@blizz.com',    password: 'password') 
  valeera   = User.create!(username: 'valeera',   email: 'valeera@blizz.com',   password: 'password') 
  tracer    = User.create!(username: 'tracer',    email: 'tracer@blizz.com',    password: 'password') 
  liming    = User.create!(username: 'liming',    email: 'liming@blizz.com',    password: 'password') 
  diablo    = User.create!(username: 'diablo',    email: 'diablo@blizz.com',    password: 'password') 
  ekko      = User.create!(username: 'ekko',      email: 'ekko@lol.com',        password: 'password') 
  ashe      = User.create!(username: 'ashe',      email: 'ashe@lol.com',        password: 'password') 
  gnar      = User.create!(username: 'gnar',      email: 'gnar@lol.com',        password: 'password') 
  sion      = User.create!(username: 'sion',      email: 'sion@lol.com',        password: 'password') 
  yasuo     = User.create!(username: 'yasuo',     email: 'yasuo@lol.com',       password: 'password') 
  jhin      = User.create!(username: 'jhin',      email: 'jhin@lol.com',        password: 'password') 

  Song.destroy_all 
  song01 = Song.create!(song_title: 'Undead Mess',            artist_id: dethklok[:id]) 
  song02 = Song.create!(song_title: 'The Other Side',         artist_id: dethklok[:id]) 
  song03 = Song.create!(song_title: 'Hindrance',              artist_id: dethklok[:id]) 
  song04 = Song.create!(song_title: 'Face 2 Face',            artist_id: dethklok[:id]) 
  song05 = Song.create!(song_title: 'Life For Me',            artist_id: pentakill[:id]) 
  song06 = Song.create!(song_title: 'Pretty Poison',          artist_id: pentakill[:id]) 
  song07 = Song.create!(song_title: 'Take Cover',             artist_id: pentakill[:id]) 
  song08 = Song.create!(song_title: 'Time To Pay',            artist_id: pentakill[:id]) 
  song09 = Song.create!(song_title: 'Dreamland',              artist_id: etc[:id]) 
  song10 = Song.create!(song_title: 'Bury The Clone',         artist_id: etc[:id]) 
  song11 = Song.create!(song_title: 'Surface',                artist_id: etc[:id]) 
  song12 = Song.create!(song_title: "Where I'm Waiting",      artist_id: etc[:id]) 
  song13 = Song.create!(song_title: 'Briefcase Full of Guts', artist_id: dethklok[:id]) 
  song14 = Song.create!(song_title: 'Birthday Dethday',       artist_id: dethklok[:id]) 
  song15 = Song.create!(song_title: 'The Cull',               artist_id: pentakill[:id]) 
  song16 = Song.create!(song_title: 'Infinity Edge',          artist_id: pentakill[:id]) 
  song17 = Song.create!(song_title: 'Punting Gnomes',         artist_id: etc[:id]) 
  song18 = Song.create!(song_title: "Lok'tar Ogar",           artist_id: etc[:id]) 
  song19 = Song.create!(song_title: 'Better Metal Snake',     artist_id: dethklok[:id]) 
  song20 = Song.create!(song_title: 'The Bloodthirster',      artist_id: pentakill[:id]) 
  song21 = Song.create!(song_title: 'More Work?!',            artist_id: etc[:id]) 
end 
